services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: coffee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/coffee
      DB_USER: postgres
      DB_PASS: postgres
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads  # nếu bạn lưu ảnh local
    # Nếu có actuator:
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:8080/actuator/health | grep -q UP || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  pgdata:
