server:
  port: ${PORT:8080}

spring:
  application:
    name: api_coffee_store
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/auth/google/callback"
            scope: openid, profile, email
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: ${SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE:5}
      minimumIdle: ${SPRING_DATASOURCE_HIKARI_MINIMUMIDLE:1}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints.web.exposure.include: health,info

jwt:
  secret: ${JWT_SECRET:change-me}
  expiration-ms: ${JWT_EXPIRATION_MS:8760}

vnpay:
  tmn_code: CHALFH6T
  hash_secret: M3JW4B80139KD92UQO0GFEE2A9JT0ZYD
  pay_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url: http://localhost:4200/payments/vnpay/return
#  ipn_url: https://caf-bay.vercel.app/payments/vnpay/ipn
  ipn_url: https://api-jsb-coffeestore.onrender.com/api/v1/payments/vnpay/ipn
  version: 2.1.0
  command: pay
  curr_code: VND
  locale: vn
  note_payment: ${NOTE_PAYMENT}